// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';

export function CreateConnection(arg1:dto.CreateConnectionRequest):Promise<dto.BaseResponse>;

export function DeleteConnection(arg1:dto.DeleteConnectionRequest):Promise<dto.BaseResponse>;

export function GetConnection(arg1:dto.GetConnectionRequest):Promise<dto.BaseResponse>;

export function ListConnections(arg1:dto.ListConnectionRequest):Promise<dto.BaseResponse>;

export function TestConnection(arg1:dto.TestConnectionRequest):Promise<dto.BaseResponse>;

export function UpdateConnection(arg1:dto.UpdateConnectionRequest):Promise<dto.BaseResponse>;
