// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateConnection(arg1) {
  return window['go']['api']['ConnectionApi']['CreateConnection'](arg1);
}

export function DeleteConnection(arg1) {
  return window['go']['api']['ConnectionApi']['DeleteConnection'](arg1);
}

export function GetConnection(arg1) {
  return window['go']['api']['ConnectionApi']['GetConnection'](arg1);
}

export function ListConnections(arg1) {
  return window['go']['api']['ConnectionApi']['ListConnections'](arg1);
}

export function TestConnection(arg1) {
  return window['go']['api']['ConnectionApi']['TestConnection'](arg1);
}

export function UpdateConnection(arg1) {
  return window['go']['api']['ConnectionApi']['UpdateConnection'](arg1);
}
