// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteData(arg1) {
  return window['go']['api']['DataApi']['DeleteData'](arg1);
}

export function ListData(arg1) {
  return window['go']['api']['DataApi']['ListData'](arg1);
}

export function PutData(arg1) {
  return window['go']['api']['DataApi']['PutData'](arg1);
}
