// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';

export function ListData(arg1:dto.ListDataRequest):Promise<dto.BaseResponse>;
