// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';

export function DeleteData(arg1:dto.DeleteDataRequest):Promise<dto.BaseResponse>;

export function ListData(arg1:dto.ListDataRequest):Promise<dto.BaseResponse>;

export function PutData(arg1:dto.PutDataRequest):Promise<dto.BaseResponse>;
