// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';

export function GetKeysTree(arg1:dto.GetKeysTreeRequest):Promise<dto.BaseResponse>;
