name: Build

on: 
  workflow_dispatch:
    inputs:
      tag:
        description: 'Version Tag'
        required: true
        default: '1.0.0'

jobs:
  release:
    name: Release MacOS 
    runs-on: macos-latest
    strategy:
      matrix:
        platform:
          - darwin/amd64
          - darwin/arm64
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.2'
          
      - name: Debug 
        run: |
          echo ${{ matrix.platform }}

      # - name: Install Wails
      #   run: |
      #     go install github.com/wailsapp/wails/v2/cmd/wails@latest
          
      # - name: Build
      #   run: |
      #     wails build

      # - name: dmg
      #   run: |
      #     dmg --source=dist --target=dist --overwrite

      # - name: Upload
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: dmg
      #     path: dist/app.dmg